<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Currency---       Dollar      Pou_e54511</name>
   <tag></tag>
   <elementGuidId>95ddaf73-ad21-4d6f-83a7-b330801c41e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='currency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#currency</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5df8ad45-3780-43ca-84b9-9f91c2016d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>c1a96be6-81a5-4ed0-b663-4082fe01a280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>8fd71f3c-6cc7-4dfe-b71c-f801c77e1e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>eee66341-9086-4ab2-949b-555f7e92857d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>2572e2e9-90cd-41e3-9a89-01365248a6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	</value>
      <webElementGuid>db2f032e-ecb4-4601-9dca-30550e081465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currency&quot;)</value>
      <webElementGuid>5ac39f29-a16f-42fb-a3eb-3c66802e7777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='currency']</value>
      <webElementGuid>e0271b03-144a-4d39-925c-98d3f0bc0f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency :'])[1]/following::select[1]</value>
      <webElementGuid>98466ba8-f4fa-4dc0-ac79-a07aba95042d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer :'])[1]/following::select[2]</value>
      <webElementGuid>2e6cd898-9525-4f21-b95b-c1da08587a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process'])[1]/preceding::select[1]</value>
      <webElementGuid>22c0a1a5-ddd5-42e4-8824-f8c9a28ee866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>da43e348-e9cc-45f9-af8e-36898112d721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency' and @id = 'currency' and (text() = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	' or . = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	')]</value>
      <webElementGuid>41b1b74b-d36a-44d7-8854-416a0909d50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
