<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1007100810091016</name>
   <tag></tag>
   <elementGuidId>e4115d23-6a45-4591-8c35-fc9bf71a8f56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='accountSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#accountSelect</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b9bf81a-c711-4e43-87e0-3dfd1e5e5d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>noAccount</value>
      <webElementGuid>a99e770c-9f5b-4cf2-bce2-636cb064b910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>account for account in Accounts</value>
      <webElementGuid>90bd19f3-0481-4e74-b332-373041a4b5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountSelect</value>
      <webElementGuid>11978f51-2fcd-4465-af71-5e7a00200ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountSelect</value>
      <webElementGuid>456136a4-f2d7-40ca-aeba-7628fd39531a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>accountNo</value>
      <webElementGuid>e1841ae7-c616-4074-bb02-318a8fe830dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>selectAcct()</value>
      <webElementGuid>b1454190-c2a7-478e-9e89-b87597f4ccf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>4ab39ea6-fa3f-49ca-bfb8-5dccaac6afe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1007100810091016</value>
      <webElementGuid>e0cbf6eb-0a1f-4120-8566-406c3e34aae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountSelect&quot;)</value>
      <webElementGuid>c76ba359-afdb-436b-b5f6-828f6787803e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='accountSelect']</value>
      <webElementGuid>972fc32e-cad1-4899-8813-0aa9f65f42c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please open an account with us.'])[1]/following::select[1]</value>
      <webElementGuid>3b4948a3-d043-4d5d-8cf0-641d106b103e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ron Weasly'])[1]/following::select[1]</value>
      <webElementGuid>d1a458e1-43dc-441c-9b91-9e82db238f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dollar'])[1]/preceding::select[1]</value>
      <webElementGuid>8ff13d9a-31cf-44c9-9ce6-efffd0b57c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8e28871e-e394-439b-88d9-bb39222e6120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'accountSelect' and @id = 'accountSelect' and (text() = '1007100810091016' or . = '1007100810091016')]</value>
      <webElementGuid>2d60b9da-0533-47d0-bec2-240be1329dba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
