<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Samsung Galaxy Tab 10.1</name>
   <tag></tag>
   <elementGuidId>99e68a52-2b68-4735-94b4-ee8560ccfe70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/form/div/table/tbody/tr[2]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.table.table-bordered > tbody > tr:nth-of-type(2) > td.text-left > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Samsung Galaxy Tab 10.1 *** Reward Points: 1000&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bef1edbe-4d73-411e-a74f-5cdf81817e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://opencart.abstracta.us:80/index.php?route=product/product&amp;product_id=49</value>
      <webElementGuid>2a398f6c-e7af-453b-94d5-1af01c1a9e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung Galaxy Tab 10.1</value>
      <webElementGuid>1e54651f-3fb7-40ea-a6bd-1749ae20461b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/form[1]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-left&quot;]/a[1]</value>
      <webElementGuid>5209152a-81ef-479e-8d64-ba39ab04993a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/div/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>a57819b2-00f0-452a-a517-ec160fb20c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Samsung Galaxy Tab 10.1')])[2]</value>
      <webElementGuid>7ed6a329-f87a-42d4-87b0-e5ca675a9685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$101.00'])[3]/following::a[2]</value>
      <webElementGuid>837819f8-664f-41ca-bcd9-93459b7c5b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$101.00'])[2]/following::a[2]</value>
      <webElementGuid>851aed7c-a77f-47ab-88c4-47cb9a0e72f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='***'])[2]/preceding::a[1]</value>
      <webElementGuid>fa1ff673-d428-43dc-85c8-db29e4684905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reward Points: 1000'])[1]/preceding::a[1]</value>
      <webElementGuid>1ff9b5e7-4566-4163-a9ca-d716f8dff980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://opencart.abstracta.us:80/index.php?route=product/product&amp;product_id=49'])[4]</value>
      <webElementGuid>dffc2682-16c2-479d-a8f5-12e692e7d5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>cfc393c3-8c7e-4e9b-acc7-dccc58fd7357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://opencart.abstracta.us:80/index.php?route=product/product&amp;product_id=49' and (text() = 'Samsung Galaxy Tab 10.1' or . = 'Samsung Galaxy Tab 10.1')]</value>
      <webElementGuid>b5881cf4-16d6-4b5d-9263-bcb5fdf6b1c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
