<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OpenCart_bitnami-close-banner-button</name>
   <tag></tag>
   <elementGuidId>ab399401-4b33-48a2-bb04-4141dcb16e82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bitnami-close-banner-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='bitnami-close-banner-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bitnami-close-banner-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b6f29418-6bed-4a5d-8567-2b5fa0e9ec76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bitnami-close-banner-button</value>
      <webElementGuid>4f5f425d-dfb3-4c2a-80d7-dad6264b3bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/bitnami/images/close.png</value>
      <webElementGuid>55d73629-2851-4a3d-997c-3e69e1221680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bitnami-close-banner-button&quot;)</value>
      <webElementGuid>7fff5a67-8118-487b-91c6-8bb08cd44887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='bitnami-close-banner-button']</value>
      <webElementGuid>abad8edb-77f1-427f-b58e-15465911b9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bitnami-banner']/img</value>
      <webElementGuid>25576a78-b7c2-4b46-a8c1-0e7c3ad39a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>4e557fa2-fb32-4d15-9e88-1e08c2153d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'bitnami-close-banner-button' and @src = '/bitnami/images/close.png']</value>
      <webElementGuid>b12f73a3-09ce-43ce-8f48-cc5c457399a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
