<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OpenCart_bitnami-close-banner-button</name>
   <tag></tag>
   <elementGuidId>7dfb4180-fbb8-4186-9cfa-4ebb975c2a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bitnami-close-banner-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='bitnami-close-banner-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bitnami-close-banner-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b7e8d5c-3e91-4862-ab64-e9f130522e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bitnami-close-banner-button</value>
      <webElementGuid>240c6fe0-b24b-4b8b-8a6c-904c28c09371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/bitnami/images/close.png</value>
      <webElementGuid>0ffd39e6-3edb-4487-b189-16ebdc1b022f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>4078273260</value>
      <webElementGuid>82e43dc8-dbe7-4def-bf8f-7558bc2b86cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>e3a0780c-eb95-412b-992a-ee178c87bbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bitnami-close-banner-button&quot;)</value>
      <webElementGuid>2273b35e-0ac8-482c-8b07-59be35f5a187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='bitnami-close-banner-button']</value>
      <webElementGuid>8d71d315-8da8-498d-af73-41786e30afde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bitnami-banner']/img</value>
      <webElementGuid>74a423d6-4e69-4df6-9ce7-76e66635e064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>a2fb368a-0ab2-46c4-acfa-925cd3c76f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'bitnami-close-banner-button' and @src = '/bitnami/images/close.png']</value>
      <webElementGuid>6327fe74-6518-4b44-8c5c-f057c0f3d29b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
