<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OpenCart_bitnami-corner-image</name>
   <tag></tag>
   <elementGuidId>e482fbbc-d58e-4712-ae6e-99536210def9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.bitnami-corner-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bitnami-banner']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Bitnami&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35518dc4-2682-46ed-afbf-a3fa7682f03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bitnami-corner-image</value>
      <webElementGuid>dafdddb5-fdb3-4c74-999e-27629440c9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bitnami</value>
      <webElementGuid>d5df8aff-dd2c-40ff-a757-81af2151c6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/bitnami/images/corner-logo.png</value>
      <webElementGuid>5f0ef816-25b8-42f7-90d2-b39354a10a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>828091947</value>
      <webElementGuid>9d3c5853-0148-4aed-b631-f4d9f0222498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>e40ce302-dfd1-4bc0-93dd-ed439be2bd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bitnami-banner&quot;)/div[@class=&quot;bitnami-corner-image-div&quot;]/a[1]/img[@class=&quot;bitnami-corner-image&quot;]</value>
      <webElementGuid>ca8b5221-6c50-4565-815c-21a949ddc440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bitnami-banner']/div/a/img</value>
      <webElementGuid>e74e6fe6-2cb2-44ee-8fd1-1705aae1112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bitnami']</value>
      <webElementGuid>3db2527e-6664-4333-b56c-b94f290e6df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>42e6990f-3fc4-4b9e-b0d3-d838e90a12fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Bitnami' and @src = '/bitnami/images/corner-logo.png']</value>
      <webElementGuid>fb544d15-0fb7-4b6c-862c-9e7215b48beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
